In [1]:
import numpy as np
arr = np.arange (0 , 10 , 1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr = np.ones((3 ,3)) > 0
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
arr = np.ones((3 ,3), dtype = bool )
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
arr = np.full((3, 3), fill_value = True, dtype = bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
import numpy as np
arr = np.arange(0, 10)
print (arr[arr%2 == 1])

[1 3 5 7 9]


In [11]:
import numpy as np
arr = np.arange (0 ,10)
arr [arr %2 ==1] = -1
print (arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [12]:
import numpy as np
arr = np.arange (10)
arr_2d = arr.reshape (2 , -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [13]:
import numpy as np
arr1 = np.arange(10).reshape(2 , -1)
arr2 = np.repeat(1, 10).reshape(2 , -1)
c = np.concatenate([ arr1 , arr2 ], axis =0)
print (" Result : \n", c )

 Result : 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [14]:
import numpy as np
arr1 = np.arange(10).reshape (2 , -1)
arr2 = np.repeat(1 ,10).reshape (2 , -1)
c = np.concatenate([ arr1 , arr2 ], axis =1)
print ("C = ", c)

C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [15]:
import numpy as np
arr = np.array([1 ,2 ,3])
print (np.repeat(arr, 3))
print (np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [16]:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) &( a <= 10) )
print ("result ", a[index])

result  [ 6  9 10]


In [17]:
import numpy as np

def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

a = np.array([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np.array([6 ,3 ,4 ,8 ,9 ,7 ,1])

pair_max = np.vectorize ( maxx , otypes = [float ])
print(pair_max(a, b ) )

[6. 7. 9. 8. 9. 7. 5.]


In [18]:
import numpy as np

a = np.array ([5, 7, 9, 8, 6, 4, 5])
b = np.array ([6, 3, 4, 8, 9, 7, 1])

print(" Result ", np.where(a < b, b, a))

 Result  [6 7 9 8 9 7 5]


In [20]:
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: d:\GitHub\AIO_Homework\advertising.csv

  0%|          | 0.00/4.06k [00:00<?, ?B/s]
100%|██████████| 4.06k/4.06k [00:00<?, ?B/s]


In [21]:
import pandas as pd
df = pd.read_csv('Week8_Data/advertising.csv')

data = df.to_numpy()

In [26]:
df['Sales'].max()

27.0

In [25]:
df[df['Sales'] == df['Sales'].max()].index

Index([175], dtype='int64')

In [27]:
np.average(df['TV'])

147.0425

In [29]:
df[df['Sales'] >= 20].count()

TV           40
Radio        40
Newspaper    40
Sales        40
dtype: int64

In [30]:
np.average(df['Radio'][df['Sales'] >= 15])

26.22293577981651

In [32]:
np.sum(df['Sales'][df['Newspaper'] >= np.average(df['Newspaper'])])

1405.1

In [ ]:
A = np.average(df['Sales'])

def compare(value):
    if value > A:
        return 'Good'
    elif value < A:
        return 'Bad'
    else:
        return 'Average'

df['Mark'] = df['Sales'].apply(compare)

# df['Mark'] = np.where(df['Sales'] > A, 'Good', np.where(df['Sales'] < A, 'Bad', 'Average'))

In [35]:
df[7:10]

,TV,Radio,Newspaper,Sales,Mark
7,120.2,19.6,11.6,13.2,Bad
8,8.6,2.1,1.0,4.8,Bad
9,199.8,2.6,21.2,15.6,Good
